function init
%{
pupl_UI_addimporter(...
    'loadfunc', @readeyelinkEDF_mex,...
    'label', 'From Eyelink &EDF (mex method)',...
    'filefilt', '*.edf')
%}
pupl_UI_addimporter(...
    'loadfunc', @readeyelinkEDF_edf2mat,...
    'label', 'From Eyelink &EDF (Edf2Mat method)',...
    'filefilt', '*.edf')
pupl_UI_addimporter(...
    'loadfunc', @readeyelinkEDF_base,...
    'label', 'From Eyelink &EDF (base method)',...
    'filefilt', '*.edf')
pupl_UI_addimporter(...
    'loadfunc', @readeyelinkASC,...
    'label', 'From Eyelink &ASCII (.asc; output of edf2asc)',...
    'filefilt', '*.asc')

end
