function init

global userInterface

if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Label', 'From &Noldus Excel file',...
        'Interruptible', 'off',...
        'Callback', @(h, e)...
            updateactivedata(@() pupl_importraw(...
                'eyedata', getactivedata,...
                'loadfunc', @loadnoldusexcel,...
                'type', 'event')));
end

end