function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Label', 'From &Noldus Excel file',...
        'Interruptible', 'off',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                userInterface.UserData.activeEyeDataIdx,...
                @() importeventlogs(getactive('eye data'), @loadnoldusexcel),...
                1));
end

end