function EYE = copyevents(EYE, eventLog, offsetParams, eventsToAttach, namesToAttach)

[matchIdx, namesIdx] = ismember({eventLog.event.type}, eventsToAttach);
times = [reshape([eventLog.event(matchIdx).time], [], 1) ones([numel(matchIdx) 1])]*offsetParams;

EYE.event = cat(2, reshape(EYE.event, 1, []),...
    reshape(struct(...
        'type', namesToAttach(namesIdx),...
        'time', {times},...
        'latency', {round(times/EYE.srate + 1)}),...
    1, []));

[~, I] = sort([EYE.event.time]);
EYE.event = EYE.event(I);

end