
function listboxregexp(parent, contents)

%   Inputs
% parent--grapgics object
% contents--cell array of char

% List box
uicontrol(parent,...
    'Style', 'listbox',...
    'Max', inf,...
    'String', contents,...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.88])
% Regular expression box
uicontrol(parent,...
    'String', 'Regular expression here...',...
    'Style', 'edit',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08],...
    'KeyReleaseFcn', @selectbyregexp)

end

function selectbyregexp(src, e)

if strcmpi(e.Key, 'return')
    listBox = findobj(src.Parent, 'Style', 'listbox');
    listBox.Value = find(~cellfun(@isempty, regexp(listBox.String, src.String)));
end

end