function EYE = trimgaze(EYE, varargin)

p = inputParser;
addParameter(p, 'lims', [])
parse(p, varargin{:});

if isempty(p.Results.lims)
    lims = UI_getgazelims(EYE);
    if isempty(lims)
        EYE = [];
        return
    end
else
    lims = p.Results.lims;
end

fprintf('Trimming extreme gaze values...\n')
for dataIdx = 1:numel(EYE)
    badIdx = EYE(dataIdx).gaze.x < lims(1) |...
        EYE(dataIdx).gaze.x > lims(2) |...
        EYE(dataIdx).gaze.y < lims(3) |...
        EYE(dataIdx).gaze.y > lims(4);
    for field1 = {'gaze' 'data'} 
        for field2 = reshape(fieldnames(EYE(dataIdx).(field1{:})), 1, [])
            EYE(dataIdx).(field1{:}).(field2{:})(badIdx) = nan; 
        end
    end
    fprintf('\t%s: %0.2f%% of data removed\n', EYE(dataIdx).name, 100*nnz(badIdx)/numel(badIdx))
end

end

function lims = UI_getgazelims(EYE)

x = mergefields(EYE, 'gaze', 'x');
y = mergefields(EYE, 'gaze', 'y');

f = figure(...
    'ToolBar', 'none',...
    'MenuBar', 'none',...
    'UserData', struct(...
        'lims', [min(x) max(x) min(y) max(y)],...
        'x', x,...
        'y', y));
p1 = uipanel(f,...
    'Tag', 'plotpanel',...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.88]);
ax = axes(p1,...
    'Tag', 'middlescatter',...
    'NextPlot', 'add',...
    'Units', 'normalized',...
    'Position', [0.21 0.21 0.78 0.78]);
axes(p1,...
    'Tag', 'bottomhist',...
    'NextPlot', 'add',...
    'Units', 'normalized',...
    'Position', [0.21 0.06 0.78 0.13]);
axes(p1,...
    'Tag', 'lefthist',...
    'NextPlot', 'add',...
    'Units', 'normalized',...
    'Position', [0.06 0.21 0.13 0.78]);
uicontrol(p1,...
    'Style', 'text',...
    'FontSize', 10,...
    'Tag', 'reporttext',...
    'String', '0%% trimmed',...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.18 0.13]);
axes(ax);
scatter(x, y);
xlimits = xlim;
ylimits = ylim;
f.UserData.lims = [xlimits ylimits];

p = uipanel(f,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08]);
uicontrol(p,...
    'Style', 'edit',...
    'Tag', 'limsedit',...
    'String', num2str(f.UserData.lims),...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.38 0.98]);
uicontrol(p,...
    'String', 'Update',...
    'Units', 'normalized',...
    'Callback', @(h,e) updateplot,...
    'Position', [0.41 0.01 0.18 0.98]);
uicontrol(p,...
    'String', 'Done',...
    'Units', 'normalized',...
    'Callback', @(h,e) uiresume(f),...
    'Position', [0.61 0.01 0.18 0.98]);
uicontrol(p,...
    'String', 'Cancel',...
    'Units', 'normalized',...
    'Callback', @(h,e) delete(f),...
    'Position', [0.81 0.01 0.18 0.98]);
    
updateplot(f);

uiwait(f);

if isvalid(f)
    lims = str2num(get(findobj(f, 'Tag', 'limsedit'), 'String'));
    close(f);
else
    lims = [];
end

end

function updateplot(varargin)

if ~isempty(varargin)
    f = varargin{cellfun(@isgraphics, varargin)};
else
    f = gcbf;
end

lims = str2num(get(findobj(f, 'Tag', 'limsedit'), 'String'));
x = f.UserData.x;
y = f.UserData.y;

badIdx = x < lims(1) |...
        x > lims(2) |...
        y < lims(3) |...
        y > lims(4);

axes(findobj(f, 'Type', 'axes', 'Tag', 'middlescatter'));
cla;
scatter(x(~badIdx), y(~badIdx), 5, 'k', 'filled',...
    'MarkerFaceAlpha', 0.1,...
    'MarkerEdgeAlpha', 0.1)
scatter(x(badIdx), y(badIdx), 5, 'r', 'filled',...
    'MarkerFaceAlpha', 0.1,...
    'MarkerEdgeAlpha', 0.1)
xlimits = xlim;
ylimits = ylim;
xticks('');
yticks('');
axes(findobj(f, 'Tag', 'bottomhist'));
cla
histogram(x)
xlim(xlimits);
yticks('');
axes(findobj(f, 'Tag', 'lefthist'));
cla
histogram(y)
xlim(ylimits)
yticks('');
set(gca,'view',[90 -90])

set(findobj(f, 'Tag', 'reporttext'), 'String', sprintf('%0.2f%% trimmed', 100*nnz(badIdx)/numel(badIdx)));

end