function binDescriptions = UI_getbindescriptions(EYE)

f = figure(...
    'MenuBar', 'none',...
    'ToolBar', 'none',...
    'NumberTitle', 'off',...
    'Name', 'Create bins',...
    'UserData', struct('binDescriptions', []));
%% Left panel
createBinsPanel = uipanel(f,...
    'Tag', 'createBinsPanel',...
    'Units', 'Normalized',...
    'Position', [0.01 0.01 0.58 0.98]);
uicontrol(createBinsPanel,...
    'Style', 'text',...
    'String', 'Name of new bin:',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.91 0.48 0.08])
uicontrol(createBinsPanel,...
    'Style', 'edit',...
    'String', 'New bin',...
    'Tag', 'binName',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.51 0.91 0.48 0.08])
uicontrol(createBinsPanel,...
    'Style', 'listbox',...
    'Tag', 'epochsBox',...
    'Max', inf,...
    'String', unique(mergefields(EYE, 'epoch', 'name')),...
    'Units', 'normalized',...
    'Position', [0.01 0.21 0.98 0.68])
uicontrol(createBinsPanel,...
    'Style', 'edit',...
    'Tag', 'regExpEditBox',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.51 0.11 0.48 0.08])
uicontrol(createBinsPanel,...
    'Style', 'pushbutton',...
    'Callback', @regexpsel,...
    'String', 'Select reg. expression:',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.48 0.08])
uicontrol(createBinsPanel,...
    'Style', 'pushbutton',...
    'String', 'Create bin',...
    'Callback', @createbin,...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08])
%% Right panel
binControlPanel = uipanel(f,...
    'Tag', 'binControlPanel',...
    'Units', 'Normalized',...
    'Position', [0.61 0.01 0.38 0.98]);
uicontrol(binControlPanel,...
    'Style', 'text',...
    'String', 'Extant bins:',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.91 0.98 0.08])
uicontrol(binControlPanel,...
    'Style', 'listbox',...
    'Tag', 'binsBox',...
    'Max', inf,...
    'Units', 'normalized',...
    'Position', [0.01 0.21 0.98 0.68])
uicontrol(binControlPanel,...
    'Style', 'pushbutton',...
    'String', 'Delete selected bins',...
    'Callback', @deletebins,...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.08])
uicontrol(binControlPanel,...
    'Style', 'pushbutton',...
    'String', 'Done',...
    'Callback', @(h,e)uiresume(f),...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08])
%%
uiwait(f);
if isvalid(f)
    binDescriptions = f.UserData.binDescriptions;
    close(f);
else
    binDescriptions = [];
end

end

function regexpsel(varargin)

f = gcbf;
re = getcomponentbytag(f, 'createBinsPanel', 'regExpEditBox');
eps = getcomponentbytag(f, 'createBinsPanel', 'epochsBox');
eps.Value = find(~cellfun(@isempty, regexp(eps.String, re.String)));

end

function createbin(varargin)

f = gcbf;
eps = getcomponentbytag(f, 'createBinsPanel', 'epochsBox');
bins = getcomponentbytag(f, 'binControlPanel', 'binsBox');
priorBinsValue = bins.Value;
binName = getcomponentbytag(f, 'createBinsPanel', 'binName');
bins.String = [bins.String; cellstr(binName.String)];

f.UserData.binDescriptions = cat(2, f.UserData.binDescriptions,...
    struct('name', binName.String,...
        'epochs', {eps.String(eps.Value)}));  

binName.String = sprintf('New bin');
bins.Value = priorBinsValue;
eps.Value = [];

end

function deletebins(varargin)

f = gcbf;
bins = getcomponentbytag(f, 'binControlPanel', 'binsBox');
f.UserData.binDescriptions(bins.Value) = [];
bins.String(bins.Value) = [];
bins.Value = [];

end