
function out = readeyetribe_csv(fullpath)

raw = readdelim2cell(fullpath, ',');
cols = raw(1, :);
contents = raw(2:end, :);
times = 86400 * datenum(contents(:, strcmp(cols, 'timestamp')), 'yyyy-mm-dd HH:MM:SS.FFF');
types = contents(:, strcmp(cols, 'message'));

[~, filename] = fileparts(fullpath);

out = struct(...
    'name', filename,...
    'src', fullpath,...
    'event',...
        struct(...
            'time', num2cell(times),...
            'type', types,...
            'rt', repmat({NaN}, size(times))));

end
