function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Label', 'From &Presentation .log file',...
        'Interruptible', 'off',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                userInterface.UserData.activeEyeDataIdx,...
                @() pupl_importraw(...
                    'eyedata', getactive('eye data'),...
                    'loadfunc', @loadpresentationlog,...
                    'type', 'event'),...
                1));
end

end