function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Text', 'From &Presentation .log file',...
        'Interruptible', 'off',...
        'MenuSelectedFcn', @(h, e)...
            updateglobals('eventLogs',...
                'append',...
                @loadpresentationlog,...
                1));
end

end