function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Label', 'From &Presentation .log file',...
        'Interruptible', 'off',...
        'Callback', @(h, e)...
            updateactivedata(@() pupl_importraw(...
                'eyedata', getactivedata,...
                'loadfunc', @loadpresentationlog,...
                'type', 'event')));
end

end