function init

pupl_UI_addimporter(...
    'loadfunc', @readeyelinkEDF,...
    'label', 'From Eyelink &EDF (beta)')
pupl_UI_addimporter(...
    'loadfunc', @readeyelinkASC,...
    'label', 'From Eyelink &ASCII (output of edf2asc)')

end