function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From Eyelink &ASCII (output of edf2asc)',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @() pupl_importraw('loadfunc', @readeyelinkASC),...
                1));
end

end