function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From Eyelink &ASCII (output of edf2asc)',...
        'Callback', @(h, e)...
            appendtodata(@() pupl_importraw(...
                'loadfunc', @readeyelinkASC)));
end

end