
function pupl_pupilsizehist(EYE)

for dataidx = 1:numel(EYE)
    approval = displaydata(EYE(dataidx));
    if isempty(approval)
        return
    end
end

end

function approval = displaydata(EYE)

f = figure(...
    'ToolBar', 'none',...
    'MenuBar', 'none',...
    'UserData', true);
p1 = uipanel(f,...
    'Tag', 'plotpanel',...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.88]);
a = axes(p1, 'Tag', 'scatter');
p = uipanel(f,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08]);
approvebutton = uicontrol(p,...
    'String', 'Next',...
    'Units', 'normalized',...
    'Callback', @(h,e) uiresume(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @() uiresume(f)),...
    'Position', [0.01 0.01 0.48 0.98]);
uicontrol(p,...
    'String', 'Quit',...
    'Units', 'normalized',...
    'Callback', @(h,e) delete(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @() delete(f)),...
    'Position', [0.51 0.01 0.48 0.98]);

pupilsizehist(a, EYE.diam.left, EYE.diam.right);
title(EYE.name, 'Interpreter', 'none');
uicontrol(approvebutton);

uiwait(f);

if isgraphics(f)
    approval = get(f, 'UserData');
    close(f);
else
    approval = [];
end

end