
function threshold = UI_cdfgetrej(data, varargin)

if numel(varargin) > 0
    lims = varargin{1};
else
    lims = [min(data) max(data)];
end

f = figure(...
    'ToolBar', 'none',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Name', 'Rejection threshold',...
    'UserData', struct(...
        'data', data,...
        'lims', lims));
axes(f,...
    'Tag', 'axis',...
    'Units', 'normalized',...
    'Position', [0.11 0.21 0.78 0.68]);
uicontrol('Style', 'edit',...
    'Tag', 'threshold',...
    'String', 'Select rejection threshold',...
    'Units', 'normalized',...
    'Callback', @(h,e)plotrejection(f),...
    'Position', [0.01 0.01 0.48 0.08]);
uicontrol('Style', 'pushbutton',...
    'Units', 'normalized',...
    'String', 'Accept',...
    'Callback', @(h,e)uiresume(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @()uiresume(f)),...
    'Position', [0.51 0.01 0.23 0.08]);
uicontrol('Style', 'pushbutton',...
    'Units', 'normalized',...
    'String', 'Cancel',...
    'Callback', @(h,e)delete(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @()delete(f)),...
    'Position', [0.76 0.01 0.23 0.08]);

plotrejection(f)
uiwait(f)
if isgraphics(f)
    threshold = getcurrthresh(f);
    close(f)
else
    threshold = [];
end

end

function plotrejection(f)

currThreshold = getcurrthresh(f);

UserData = get(f, 'UserData');
data = UserData.data;
lims = UserData.lims;

thresholds = linspace(lims(1), lims(2), 1000);   
ppnViolating = sum(bsxfun(@ge, data', thresholds))/numel(data);
currPpnViolating = nnz(data >= currThreshold)/numel(data);
ax = findobj(f, 'Tag', 'axis');
axes(ax); cla; hold on
plot(thresholds, ppnViolating, 'k');
plot(repmat(currThreshold, 1, 2), [0 1], '--k')
plot(lims, repmat(currPpnViolating, 1, 2), '--k')
xlim(lims);
ylim([0 1]);
xlabel('Threshold');
ylabel('Proportion violating threshold');

end

function thresh = getcurrthresh(f)

teditbox = findobj(f, 'Tag', 'threshold');
thresh = str2double(get(teditbox, 'String'));

end