
function pupl_event_view(h, EYE)

if isempty(which('uitable'))
    all_events = mergefields(EYE, 'event');
    listbox_contents = cell(all_events);

    for idx = 1:numel(all_events)
        listbox_contents{idx} = sprintf('%d. [%fs]: %s', idx, all_events(idx).time, all_events(idx).name);
    end
    lb = uicontrol(h,...
        'Style', 'listbox',...
        'String', listbox_contents,...
        'Max', inf,...
        'Units', 'normalized',...
        'Position', [0.01 0.01 0.98 0.98]);
else
    % Get cell array data for UI table
    [data, colnames] = pupl_event_toUITcell(EYE.event);
    uit = uitable(h,...
        'Data', data,...
        'ColumnName', colnames,...
        'Units', 'normalized',...
        'Position', [0.01 0.01 0.98 0.98]);
end

end