
function sel = pupl_event_selUI(EYE, varargin)

if numel(varargin) < 1
    prompt = 'Select events';
else
    prompt = varargin{1};
end
if numel(varargin) < 2
    buttons = true;
else
    buttons = varargin{2};
end
if numel(varargin) < 3
    listbox_str = {};
else
    listbox_str = varargin{3};
end
if numel(varargin) < 4
    all_events = mergefields(EYE, 'event');
else
    all_events = varargin{4};
end

% Main figure
f = figure(...
    'UserData', struct(...
        'events', all_events,...
        'n', 0),...
    'Name', 'Event filter',...
    'NumberTitle', 'off',...
    'Menu', 'none');
% Prompt
uicontrol(f,...
    'Style', 'text',...
    'String', prompt,...
    'Units', 'normalized',...
    'Position', [0.01 0.91 0.98 0.08]);
% Listbox in which event names are displayed
if isempty(listbox_str)
    for dataidx = 1:numel(EYE)
        curr_evs = EYE(dataidx).event(:)';
        rec_names = repmat({sprintf('[%s]', EYE(dataidx).name)}, size(curr_evs));
        event_ns = cellfun(@(x) sprintf('%d.', x), num2cell(1:numel(curr_evs)), 'UniformOutput', false);
        event_times = cellfun(@(x) sprintf('[%ss]', num2str(x)), {curr_evs.time}, 'UniformOutput', false);
        event_names = {curr_evs.name};
        listbox_str{end + 1} = strcat(...
            rec_names,...
            {' '},...
            event_ns,...
            {' '},...
            event_times,...
            {' '},...
            event_names);
    end
    listbox_str = [listbox_str{:}];
end

uicontrol(f,...
    'Style', 'listbox',...
    'Max', inf,...
    'Tag', 'listbox',...
    'String', listbox_str,...
    'Units', 'normalized',...
    'Position', [0.01 0.21 0.98 0.68])
p1 = uipanel(f,...
    'Title', 'Regular expression filter',...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.48 0.08]);
uicontrol(p1,...
    'Style', 'edit',...
    'String', 'regular expression filter',...
    'Tag', 'regexp',...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.98],...
    'Callback', @(h,e) update_listbox({1 get(h, 'String')}),...
    'KeyPressFcn', @(h,e) enterdo(e, @() update_listbox({1 get(h, 'String')})));
p2 = uipanel(f,...
    'Title', 'Event variable filter',...
    'Units', 'normalized',...
    'Position', [0.51 0.11 0.48 0.08]);
uicontrol(p2,...
    'Style', 'edit',...
    'String', 'event var filter (e.g. #rt < 0.1)',...
    'Tag', 'evar',...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.98],...
    'Callback', @(h,e) update_listbox({2 get(h, 'String')}),...
    'KeyPressFcn', @(h,e) enterdo(e, @() update_listbox({2 get(h, 'String')})));
if buttons
    uicontrol(f,...
        'String', 'Use highlighted',...
        'Units', 'normalized',...
        'Position', [0.01 0.01 0.23 0.08],...
        'Callback', @(h,e) finish_sel(0),...
        'KeyPressFcn', @(h,e) enterdo(e, @() finish_sel(0)));
    uicontrol(f,...
        'String', 'Use regexp filter',...
        'Units', 'normalized',...
        'Position', [0.26 0.01 0.23 0.08],...
        'Callback', @(h,e) finish_sel(1),...
        'KeyPressFcn', @(h,e) enterdo(e, @() finish_sel(1)));
    uicontrol(f,...
        'String', 'Use event var filter',...
        'Units', 'normalized',...
        'Position', [0.51 0.01 0.23 0.08],...
        'Callback', @(h,e) finish_sel(2),...
        'KeyPressFcn', @(h,e) enterdo(e, @() finish_sel(2)));
    uicontrol(f,...
        'String', 'Cancel',...
        'Units', 'normalized',...
        'Position', [0.76 0.01 0.23 0.08],...
        'Callback', @(h,e) delete(f),...
        'KeyPressFcn', @(h,e) enterdo(e, @() delete(f)));
else
    uicontrol(f,...
        'String', 'Done',...
        'Units', 'normalized',...
        'Position', [0.76 0.01 0.23 0.08],...
        'Callback', @(h,e) delete(f),...
        'KeyPressFcn', @(h,e) enterdo(e, @() delete(f)));
end
uiwait(f);
if isgraphics(f)
    ud = get(f, 'UserData');
    listbox = findobj(f, 'Style', 'listbox');
    switch ud.n
        case 0
            contents = get(listbox, 'String');
            idx = get(listbox, 'Value');
            sel = {ud.n ud.events(idx).name};
        case 1
            sel = {ud.n get(findobj(f, 'Tag', 'regexp'), 'String')};
        case 2
            sel = {ud.n get(findobj(f, 'Tag', 'evar'), 'String')};
    end
    close(f);
else
    sel = [];
end

end

function update_listbox(filter)

f = gcbf;
ud = get(f, 'UserData');
idx = find(pupl_event_sel(ud.events, filter));
listbox = findobj(f, 'Tag', 'listbox');
set(listbox, 'Value', idx);

end

function finish_sel(n)

f = gcbf;
ud = get(f, 'UserData');
ud.n = n;
set(f, 'UserData', ud);
uiresume(f);

end
