function init

pupl_UI_addimporter(...
    'loadfunc', @readtobii,...
    'label', 'From &Tobii Excel (.xlsx) file (not recommended)',...
    'argstoself', {'xls'})
pupl_UI_addimporter(...
    'loadfunc', @readtobii,...
    'label', 'From &Tobii Tab-delimited (tsv/tdf/txt) file',...
    'argstoself', {'tab'})
pupl_UI_addimporter(...
    'loadfunc', @readtobii,...
    'label', 'From &Tobii Comma-separated (csv/txt) file',...
    'argstoself', {'csv'})

end