function init

global userInterface
if isgraphics(userInterface)
    tobiimenu = uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From &Tobii Pro Studio');
    uimenu(tobiimenu,...
        'Label', 'E&xcel file',...
        'Callback', @(h, e)...
            appendtodata(@() pupl_importraw(...
                'loadfunc', @loadtobii,...
                'args', {'xls'})));
    uimenu(tobiimenu,...
        'Label', '&Tab-delimited (tsv/tdf/txt) file',...
        'Callback', @(h, e)...
            appendtodata(@() pupl_importraw(...
                'loadfunc', @loadtobii,...
                'args', {'tab'})));
end

end