function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Text', 'From &Tobii Excel file',...
        'Interruptible', 'off',...
        'MenuSelectedFcn', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @loadtobiiexcel,...
                1));
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Text', 'From &Tobii Excel file',...
        'Interruptible', 'off',...
        'MenuSelectedFcn', @(h, e)...
            updateglobals('eventLogs',...
                'append',...
                @() loadtobiiexcel('as', 'event logs'),...
                1));
end

end