function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEventLogsMenu'),...
        'Label', 'From &xdf',...
        'Interruptible', 'off',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @load_xdf,...
                1));
end

end