function init

global userInterface

if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From &XDF',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @() pupl_importraw(...
                    'type', 'eye',...
                    'loadfunc', @sub_xdfimport),...
                1));
end

end