function out = getactivedata

global userInterface

out = subsref(...
    evalin('base', 'eyeData'),...
    struct(...
        'type', '()',...
        'subs', {{getfield(get(userInterface, 'UserData'), 'activeEyeDataIdx')}}...
    )...
);

end