
function listboxregexp(parent, contents)

%   Inputs
% parent--grapgics object
% contents--cell array of char

% List box
uicontrol(parent,...
    'Style', 'listbox',...
    'Max', inf,...
    'String', contents,...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.88])
% Regular expression box
uicontrol(parent,...
    'String', 'regexp',...
    'Style', 'edit',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.98 0.08],...
    'Callback', @(h,e) selectbyregexp(h),...
    'KeyReleaseFcn', @(h,e) enterdo(e, @() selectbyregexp(h)))

end

function selectbyregexp(src)

listBox = findobj(src.Parent, 'Style', 'listbox');
listBox.Value = find(~cellfun(@isempty, regexp(listBox.String, src.String)));

end