function pupl_UI

global userInterface

userInterface = figure('Name', 'Pupillometry',...
    'NumberTitle', 'off',...
    'UserData', struct(...
        'dataCount', 0,...
        'eventLogCount', 0,...
        'activeEyeDataIdx', logical([]),...
        'activeEventLogsIdx', logical([])),...
    'SizeChangedFcn', @preservelayout,...
    'DeleteFcn', @savewarning,...
    'MenuBar', 'none',...
    'ToolBar', 'none',...
    'Visible', 'off');

% Active datasets
uibuttongroup('Title', 'Active datasets',...
    'Tag', 'activeEyeDataPanel',...
    'Position',[0.01 0.01 .48 0.95],...
    'FontSize', 10);
uibuttongroup('Title', 'Active event logs',...
    'Tag', 'activeEventLogsPanel',...
    'Position',[0.51 0.01 .48 0.95],...
    'FontSize', 10);

% File menu
fileMenu = uimenu(userInterface,...
    'Tag', 'fileMenu',...
    'Text', '&File');
uimenu(fileMenu,...
    'Text', '&Import',...
    'MenuSelectedFcn', @(h, e)...
        updateglobals(pupl_format('type', 'eye data'), 'append'));
uimenu(fileMenu,...
    'Text', '&Load',...
    'MenuSelectedFcn', @(h, e)...
        updateglobals(pupl_load('type', 'eye data'), 'append'));
uimenu(fileMenu,...
    'Text', '&Save',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_save('type', 'eye data', 'data', getactiveeyedata)));
uimenu(fileMenu,...
    'Text', '&Remove active datasets',...
    'Separator', 'on',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(deleteactive('eye data')));

% Processing menu
processingMenu = uimenu(userInterface, 'Text', '&Process');
uimenu(processingMenu,...
    'Text', 'Identify &blinks',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(identifyblinks(getactiveeyedata)));
uimenu(processingMenu,...
    'Text', '&Moving average filter',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(eyefilter(getactiveeyedata)));
uimenu(processingMenu,...
    'Text', '&Interpolate',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(interpeyedata(getactiveeyedata)));
uimenu(processingMenu,...
    'Text', '&Merge left and right streams',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(mergelr(getactiveeyedata)));

% Epoching menu
trialsMenu = uimenu(userInterface,...
    'Text', '&Trials');
uimenu(trialsMenu,...
    'Text', '&Separate into trials',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(epoch(getactiveeyedata)));
uimenu(trialsMenu,...
    'Text', '&Merge trials',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(binepochs(getactiveeyedata)));
% Event logs sub-menu
eventLogsMenu = uimenu(trialsMenu,...
    'Text', '&Event logs');
uimenu(eventLogsMenu,...
    'Text', '&Write to eye data',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(attachevents(getactiveeyedata, 'eventLogs', geteventlogs)));
uimenu(eventLogsMenu,...
    'Text', '&Import',...
    'Separator', 'on',...
    'Interruptible', 'off',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_format('type', 'event logs'), 'append'));
uimenu(eventLogsMenu,...
    'Text', '&Load',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_load('type', 'event logs'), 'append'));
uimenu(eventLogsMenu,...
    'Text', '&Save',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_save('type', 'eye data', 'data', geteventlogs)));
uimenu(eventLogsMenu,...
    'Text', '&Remove active event logs',...
    'Separator', 'on',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(deleteactive('event logs')));
    
% Experiment menu
experimentMenu = uimenu(userInterface,...
    'Text', '&Experiment');
uimenu(experimentMenu,...
    'Text', '&Assign datasets to conditions',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_condition(getactiveeyedata)));
uimenu(experimentMenu,...
    'Text', '&Merge conditions',...
    'MenuSelectedFcn', @(src, event)...
        updateglobals(pupl_merge(getactiveeyedata)));

% Plotting menu
plottingMenu = uimenu(userInterface,...
    'Text', 'P&lot');
uimenu(plottingMenu,...
    'Text', 'Plot &continuous',...
    'MenuSelectedFcn', @(src, event)...
        plotcontinuous(getactiveeyedata));
plotTrialsMenu = uimenu(plottingMenu,...
    'Text', 'Plot &trials');
uimenu(plotTrialsMenu,...
    'Text', '&Line plot',...
    'MenuSelectedFcn', @(src, event)...
        plottrials(getactiveeyedata));
uimenu(plotTrialsMenu,...
    'Text', '&Heatmap',...
    'MenuSelectedFcn', @(src, event)...
        eyeheatmap(getactiveeyedata));
uimenu(plottingMenu,...
    'Text', 'Pupil &foreshortening error surface',...
    'MenuSelectedFcn', @(h, e)...
        PFEplot(getactiveeyedata));

% Spreadsheet menu
spreadSheetMenu = uimenu(userInterface,...
    'Text', '&Spreadsheet');
uimenu(spreadSheetMenu,...
    'Text', '&Write eye data to spreadsheet',...
    'MenuSelectedFcn', @(src, event)...
        writetospreadsheet(getactiveeyedata));
    
userInterface.Visible = 'on';
    
end