function lims = UI_histgetrej(data, varargin)

p = inputParser;
addParameter(p, 'dataname', 'data');
parse(p, varargin{:});

dataname = p.Results.dataname;

f = figure(...
    'ToolBar', 'none',...
    'MenuBar', 'none',...
    'UserData', data);
p = uipanel(f,...
    'Tag', 'plotpanel',...
    'Units', 'normalized',...
    'Position', [0.01 0.11 0.98 0.88]);
axes(p,...
    'Tag', 'hist',...
    'NextPlot', 'add');
p = uipanel(f,...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.48 0.08]);
uicontrol(p,...
    'Style', 'edit',...
    'Tag', 'lower',...
    'Callback', @(h,e) updateplot(f, dataname),...
    'String', 'lower cutoff',...
    'Units', 'normalized',...
    'Position', [0.01 0.01 0.48 0.98]);
uicontrol(p,...
    'Style', 'edit',...
    'Tag', 'upper',...
    'Callback', @(h,e) updateplot(f, dataname),...
    'String', 'upper cutoff',...
    'Units', 'normalized',...
    'Position', [0.51 0.01 0.48 0.98]);
p = uipanel(f,...
    'Units', 'normalized',...
    'Position', [0.51 0.01 0.48 0.08]);
uicontrol(p,...
    'String', 'Done',...
    'Units', 'normalized',...
    'Callback', @(h,e) uiresume(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @() uiresume(f)),...
    'Position', [0.01 0.01 0.48 0.98]);
uicontrol(p,...
    'String', 'Cancel',...
    'Units', 'normalized',...
    'Callback', @(h,e) delete(f),...
    'KeyPressFcn', @(h,e) enterdo(e, @() delete(f)),...
    'Position', [0.51 0.01 0.48 0.98]);

updateplot(f, dataname);

uiwait(f);

if isgraphics(f)
    lims{1} = getlim(f, 'lower');
    lims{2} = getlim(f, 'upper');
    close(f);
else
    lims = [];
end

end

function updateplot(f, dataname)

data = get(f, 'UserData');

badidx = false(size(data));

for limType = {'lower' 'upper'}
    currLim = parsedatastr(getlim(f, limType), data);
    if strcmp(limType, 'lower')
        badidx = badidx | data < currLim;
    else
        badidx = badidx | data > currLim;
    end
end

n = 4*log2(numel(data));
x1 = min(data);
x2 = max(data);
c = [x1:(x2-x1)/(n-1):x2 x2+(x2-x1)/(n-1)];

axes(findobj(f, 'Type', 'axes', 'Tag', 'hist'));
cla;

hist(data(~badidx), c);
h = findobj(gca,'Type','patch');
set(h, 'EdgeColor', 'w');
set(findobj(gca,'Type','line'), 'Marker', 'none');

xlabel(dataname);
ylabel('Count');

title(sprintf('%0.2f%% trimmed', 100*nnz(badidx)/numel(badidx)));

end

function currStr = getlim(f, limType)

limType = cellstr(limType);
currStr = get(findobj(f, 'Tag', limType{:}), 'String');

end