function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From &EDF',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @() pupl_importraw('loadfunc', @pupl_loadEDF),...
                1));
end
if exist('OCTAVE_VERSION', 'builtin') ~= 0 &&...
        isempty(which('edfimporter'))
    % Must compile for Octave
    [~, currdir] = which(mfilename);
    mkoctfile('--mex', which('edfimporter.cpp'));
end

end