function init

global userInterface
if isgraphics(userInterface)
    uimenu(findobj(userInterface, 'Tag', 'importEyeDataMenu'),...
        'Label', 'From &EDF',...
        'Callback', @(h, e)...
            updateglobals('eyeData',...
                'append',...
                @() pupl_importraw(@pupl_loadEDF),...
                1));
end

end